FROM python:3.12-slim

WORKDIR /app

# System deps for librosa / soundfile
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        ffmpeg libsndfile1 && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY backend/ backend/
COPY main.py .
COPY ingest.py .

EXPOSE 8000

CMD ["python", "main.py"]
